version: '2'

services:
  imgproc:
    build:
      context: .
    container_name: imgproc
    volumes:
      - ./data:/imgproc/uploads:rw
    ports:
      - 127.0.0.1:8081:80
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TIME_ZONE=Asia/Novosibirsk
